added new js
CECurtiss/parks-and-weather-app pull request #22
Opened 2022-10-28 01:12 UTC by panncho453

2022-10-28 01:16 UTC, CECurtiss commented on assets/park.js
> +Storage.getitem(parkcode)
Delete line 2

2022-10-28 01:17 UTC, CECurtiss commented on assets/park.js
> +    var parkcodesearch = storage.getitem(parkcode)
camel case Item in getItem

2022-10-28 01:18 UTC, CECurtiss requested changes, later dismissed
edit a few lines

2022-10-31 17:30 UTC, DeadEye44 approved these changes

2022-10-31 17:45 UTC, DeadEye44 commented
Will need to create a new pull request for this and make all changes before pushing it.

2022-10-31 17:45 UTC, DeadEye44 approved these changes

2022-10-31 17:46 UTC, merged